# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\x12\x04sell\"\'\n\x05Login\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\">\n\x0bPriceIDPack\x12\r\n\x05price\x18\x01 \x01(\x05\x12\x10\n\x08sellerId\x18\x02 \x01(\t\x12\x0e\n\x06itemId\x18\x03 \x01(\t\"D\n\x0eQuantityIDPack\x12\x10\n\x08quantity\x18\x01 \x01(\x05\x12\x10\n\x08sellerId\x18\x02 \x01(\t\x12\x0e\n\x06itemId\x18\x03 \x01(\t\",\n\x0cSellerRating\x12\r\n\x05posFb\x18\x01 \x01(\x05\x12\r\n\x05negFb\x18\x02 \x01(\x05\"\x85\x01\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x04 \x01(\t\x12\x10\n\x08keywords\x18\x05 \x01(\t\x12\x0c\n\x04\x63ond\x18\x06 \x01(\x05\x12\x10\n\x08quantity\x18\x07 \x01(\x05\x12\x10\n\x08sellerId\x18\x08 \x01(\t\"\x1a\n\tItemPrice\x12\r\n\x05price\x18\x01 \x01(\x05\"*\n\x06IDPack\x12\x10\n\x08sellerId\x18\x01 \x01(\t\x12\x0e\n\x06itemId\x18\x02 \x01(\t\"`\n\x06Seller\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0b\n\x03pwd\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\r\n\x05items\x18\x04 \x01(\x05\x12\r\n\x05posFb\x18\x05 \x01(\x05\x12\r\n\x05negFb\x18\x06 \x01(\x05\",\n\x0eUpdateResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\".\n\x11\x44isplayItemsReply\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.sell.Item2\xfe\x02\n\x04Sell\x12\x33\n\rCreateAccount\x12\x0c.sell.Seller\x1a\x14.sell.UpdateResponse\x12.\n\tGetUserID\x12\x0b.sell.Login\x1a\x14.sell.UpdateResponse\x12\x33\n\x0fGetSellerRating\x12\x0c.sell.UserID\x1a\x12.sell.SellerRating\x12/\n\x0bItemForSale\x12\n.sell.Item\x1a\x14.sell.UpdateResponse\x12:\n\x0f\x43hangeSalePrice\x12\x11.sell.PriceIDPack\x1a\x14.sell.UpdateResponse\x12\x38\n\nRemoveItem\x12\x14.sell.QuantityIDPack\x1a\x14.sell.UpdateResponse\x12\x35\n\x0c\x44isplayItems\x12\x0c.sell.UserID\x1a\x17.sell.DisplayItemsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGIN']._serialized_start=22
  _globals['_LOGIN']._serialized_end=61
  _globals['_USERID']._serialized_start=63
  _globals['_USERID']._serialized_end=83
  _globals['_PRICEIDPACK']._serialized_start=85
  _globals['_PRICEIDPACK']._serialized_end=147
  _globals['_QUANTITYIDPACK']._serialized_start=149
  _globals['_QUANTITYIDPACK']._serialized_end=217
  _globals['_SELLERRATING']._serialized_start=219
  _globals['_SELLERRATING']._serialized_end=263
  _globals['_ITEM']._serialized_start=266
  _globals['_ITEM']._serialized_end=399
  _globals['_ITEMPRICE']._serialized_start=401
  _globals['_ITEMPRICE']._serialized_end=427
  _globals['_IDPACK']._serialized_start=429
  _globals['_IDPACK']._serialized_end=471
  _globals['_SELLER']._serialized_start=473
  _globals['_SELLER']._serialized_end=569
  _globals['_UPDATERESPONSE']._serialized_start=571
  _globals['_UPDATERESPONSE']._serialized_end=615
  _globals['_DISPLAYITEMSREPLY']._serialized_start=617
  _globals['_DISPLAYITEMSREPLY']._serialized_end=663
  _globals['_SELL']._serialized_start=666
  _globals['_SELL']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
